version: '3.1'
services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
