spring:
  application:
    name: portfolio-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

server:
  port: 8080
